In [1]:
import numpy as np
import pandas as pd

Creating an Object

In [ ]:
s= pd.Series([1,3,5,7,8,9,np.nan])
s

In [ ]:
dates = pd.date_range("20201201",periods=6)
dates

In [2]:
dates = pd.date_range("20201201",periods=16)

df=pd.DataFrame(np.random.randn(16,2),index=dates, columns=list("AB"))
df

                   A         B
2020-12-01 -1.011728 -0.741272
2020-12-02  0.167960  0.077040
2020-12-03 -0.010452  0.755185
2020-12-04  1.125235 -1.789333
2020-12-05  0.765231  0.033408
2020-12-06  0.154945 -0.454758
2020-12-07  0.624540  2.995243
2020-12-08 -0.919348  0.629095
2020-12-09 -1.924884 -0.217947
2020-12-10 -0.119378  0.659934
2020-12-11 -1.207645 -0.591426
2020-12-12  0.705031 -1.154826
2020-12-13  0.177314 -0.740595
2020-12-14 -0.164601  1.878007
2020-12-15 -0.400678  0.951732
2020-12-16 -0.010474  0.345129

In [4]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20210701"),
        "C": pd.Series(1, index=list(range(4)),dtype="float32"),
        "D": np.array([2]*4,dtype="int32"),
        "E": pd.Categorical(["Test","Train","Late","Lead"]),
        "F": "Check",
    }
)
df2

     A          B    C  D      E      F
0  1.0 2021-07-01  1.0  2   Test  Check
1  1.0 2021-07-01  1.0  2  Train  Check
2  1.0 2021-07-01  1.0  2   Late  Check
3  1.0 2021-07-01  1.0  2   Lead  Check

In [ ]:
df2.dtypes

In [ ]:
df.head(5)
df2.head(2)

In [ ]:
df.tail(2)

In [ ]:
df2.index

In [ ]:
df.to_numpy()

In [ ]:
df2.numpy()

In [3]:
df.describe()

               A          B
count  16.000000  16.000000
mean   -0.128058   0.164664
std     0.808068   1.175741
min    -1.924884  -1.789333
25%    -0.530345  -0.628718
50%    -0.010463   0.055224
75%     0.289120   0.683747
max     1.125235   2.995243

In [5]:
df2.T

,0,1,2,3
A,1.0,1.0,1.0,1.0
B,2021-07-01 00:00:00,2021-07-01 00:00:00,2021-07-01 00:00:00,2021-07-01 00:00:00
C,1.0,1.0,1.0,1.0
D,2,2,2,2
E,Test,Train,Late,Lead
F,Check,Check,Check,Check

In [10]:
df.sort_index(axis=0, ascending= False)

                   A         B
2020-12-16 -0.010474  0.345129
2020-12-15 -0.400678  0.951732
2020-12-14 -0.164601  1.878007
2020-12-13  0.177314 -0.740595
2020-12-12  0.705031 -1.154826
2020-12-11 -1.207645 -0.591426
2020-12-10 -0.119378  0.659934
2020-12-09 -1.924884 -0.217947
2020-12-08 -0.919348  0.629095
2020-12-07  0.624540  2.995243
2020-12-06  0.154945 -0.454758
2020-12-05  0.765231  0.033408
2020-12-04  1.125235 -1.789333
2020-12-03 -0.010452  0.755185
2020-12-02  0.167960  0.077040
2020-12-01 -1.011728 -0.741272

In [11]:
df.sort_values(by="B")

                   A         B
2020-12-04  1.125235 -1.789333
2020-12-12  0.705031 -1.154826
2020-12-01 -1.011728 -0.741272
2020-12-13  0.177314 -0.740595
2020-12-11 -1.207645 -0.591426
2020-12-06  0.154945 -0.454758
2020-12-09 -1.924884 -0.217947
2020-12-05  0.765231  0.033408
2020-12-02  0.167960  0.077040
2020-12-16 -0.010474  0.345129
2020-12-08 -0.919348  0.629095
2020-12-10 -0.119378  0.659934
2020-12-03 -0.010452  0.755185
2020-12-15 -0.400678  0.951732
2020-12-14 -0.164601  1.878007
2020-12-07  0.624540  2.995243

In [15]:
df[0:4]

                   A         B
2020-12-01 -1.011728 -0.741272
2020-12-02  0.167960  0.077040
2020-12-03 -0.010452  0.755185
2020-12-04  1.125235 -1.789333

In [17]:
df.loc[dates[2]]

A   -0.010452
B    0.755185
Name: 2020-12-03 00:00:00, dtype: float64

In [21]:
df.loc["20201201":"20201205",["A"]]

                   A
2020-12-01 -1.011728
2020-12-02  0.167960
2020-12-03 -0.010452
2020-12-04  1.125235
2020-12-05  0.765231

In [22]:
df.at[dates[1],"A"]

np.float64(0.16795999587062485)

In [23]:
df.iloc[3]

A    1.125235
B   -1.789333
Name: 2020-12-04 00:00:00, dtype: float64

In [24]:
df[df["A"]>1]

                   A         B
2020-12-04  1.125235 -1.789333

In [ ]:
df2["New"]=[1,2,3,4]
df2

     A          B    C  D      E      F  New
0  1.0 2021-07-01  1.0  2   Test  Check    1
1  1.0 2021-07-01  1.0  2  Train  Check    2
2  1.0 2021-07-01  1.0  2   Late  Check    3
3  1.0 2021-07-01  1.0  2   Lead  Check    4

: